# 开发环境配置
server:
  port: 8090

spring:
  # 暂无数据源配置
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

# 日志配置
logging:
  level:
    com.generate3d: debug
    org.springframework.security: debug
    org.mybatis: debug
  file:
    name: logs/generate3d-dev.log

# 文件上传路径
app:
  file:
    upload-path: ./uploads/dev/
  
  # JWT配置
  jwt:
    secret: generate3d-jwt-secret-key-2024-secure-256bit-compliant-key-for-hmac-sha-algorithm
    expiration: 86400000  # 24小时
  
  # AI服务配置（开发环境）
  ai:
    hunyuan:
      secret-id: ${HUNYUAN_SECRET_ID:AKID65sW7WjkZJ1a7eyW4c1JZinfJkxxkGah}
      secret-key: ${HUNYUAN_SECRET_KEY:PdeWDhy50kHalqDb3So4AE7mJdnpogTC}